module id_ex_reg (
    input clk,
    input reset,
    input clear,

    input RegWriteD,
    input ResultSrcD,
    input MemWriteD,
    input JumpD,
    input BranchD,
    input [2:0] ALUControlD,
    input ALUSrcD,
    input [31:0] rd1D,
    input [31:0] rd2D,
    input [31:0] pcD,
    input [31:0] rs1D,
    input [31:0] rs2D,
    input [31:0] rdD,
    input [31:0] ExtImmD,
    input [31:0] PCPlus4D,
    input [31:0] instrD,

    output RegWriteE,
    output ResultSrcE,
    output MemWriteE,
    output JumpE,
    output BranchE,
    output [2:0] ALUControlE,
    output ALUSrcE,
    output [31:0] rd1E,
    output [31:0] rd2E,
    output [31:0] pcE,
    output [31:0] rs1E,
    output [31:0] rs2E,
    output [31:0] rdE,
    output [31:0] ExtImmE,
    output [31:0] PCPlus4E,
    output [31:0] instrE,
)
